apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-configmap
data:
    initdb.sql: |-
        CREATE DATABASE IF NOT EXISTS `authdb`;
        CREATE DATABASE IF NOT EXISTS `users`;
        CREATE DATABASE IF NOT EXISTS `random`;
    database_url: jdbc:mysql://mysql-service/authdb
