---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-microservice
spec:
    selector:
        matchLabels:
            app: auth-microservice
    replicas: 1
    template:
        metadata:
            labels:
                app: auth-microservice
        spec:
            containers:
                - name: auth-microservice
                  image: samirz5/auth-service
                  ports:
                      - containerPort: 8082
                  env:
                      -   name: SPRING_DATASOURCE_URL
                          valueFrom:
                              configMapKeyRef:
                                  name: mysql-configmap
                                  key: database_url
                      -   name: SPRING_DATASOURCE_USERNAME
                          value: root
#                          valueFrom:
#                              secretKeyRef:
#                                  key: mysql-user-username
#                                  name: mysql-secret
                      -   name: SPRING_DATASOURCE_PASSWORD
#                          value: root
                          valueFrom:
                              secretKeyRef:
                                  key: mysql-user-password
                                  name: mysql-secret

# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
    name: auth-microservice
    labels:
        app: auth-microservice
spec:
    ports:
        - name: http
          port: 8082    # Port inside the cluster
          #targetPort: 8082  # Port exposed to the outside
    selector:
        app: auth-microservice
    type: ClusterIP
